### PR TITLE
Added drawing class names and build updated

### PR DESCRIPTION
**Pull request by jraska**
Added drawing class names functionality described in #21 and build configuration was updated for latest versions of used tools.
##### Drawing class names

When it is enabled, simple class name is rendered for view. When there is id as well, class name is rendered under it.
screen
##### Gradle build update

Update Gradle configuration for newest Gradle distribution and Android Gradle plugin.
Updated and tested new Travis configuration.

### CODE REVIEW

**Comment by JakeWharton** [comment]
I question if this is _too_ much information to try and cram in...

**Comment by jraska** [comment]
Well, I wanted just add class names drawing, but build was out of date so I had to update it if I wanted to build the project.

**Comment by MarcinOrlowski** [comment]
I second the idea - this is useful information to see sometimes. Yet, other could may different needs, but it'd be beneficial to ditch the whole feature because of that - what about having this configurable?

**Comment by jraska** [comment]
It is configurable with ```setDrawClassNames``` method.

**Pull request closed without merging**
